
#### general settings
name: LoL_v2

use_tb_logger: true
model: MHFlow
distortion: sr
scale: 1
gpu_ids: [0]
dataset: LoL_v2
optimize_all_z: false
cond_encoder: ConEncoder1
train_gt_ratio: 0.5
avg_color_map: false

concat_histeq: false
histeq_as_input: false
concat_color_map: false
gray_map: false # concat 1-input.mean(dim=1) to the input

align_condition_feature: false
align_weight: 0.001
align_maxpool: true

to_yuv: false

encode_color_map: false

le_curve: false
# sigmoid_output: true

#### datasets
datasets:
  train:
    # name: LoLv2
    root: /home/linuxu/Desktop/Project/datasets/LOLv2 (copy) # dataset path
    quant: 32
    use_shuffle: true
    n_workers: 3   # per GPU
    batch_size: 4 # 12
    use_flip: true
    color: RGB
    use_crop: true
    GT_size: 160 # 192
    noise_prob: 0
    noise_level: 5
    log_low: false

  val:
    root: /home/linuxu/Desktop/Project/datasets/LOLv2 (copy)
    n_workers: 3
    quant: 32
    n_max: 20
    batch_size: 1 # must be 1
    log_low: false

#### Test Settings
dataroot_unpaired: 
dataroot_GT: /home/linuxu/Desktop/Project/datasets/LOL_dataset/eval15/high
dataroot_LR: /home/linuxu/Desktop/Project/datasets/LOL_dataset/eval15/low
model_path: /home/linuxu/Desktop/Results/models/ksFlow/LOL_best_psnr_G.pth
heat: 0 # This is the standard deviation of the latent vectors

#### network structures
network_G:
  which_model_G: MHFlow
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 24 #
  train_RRDB: true
  train_RRDB_delay: 0.5

  flow:
    K: 6 # 24.49 psnr用的12 # 16
    L: 3 # 4
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: false
    fea_up0: true
    stackRRDB:
      blocks: [ 5 ]
      concat: true

#### path
path:
  # pretrain_model_G: ../pretrained_models/RRDB_DF2K_8X.pth
  root: ./
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 2e-4
  weight_decay_G: 0 #1e-5 # 1e-5 # 5e-5 # 1e-5
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: 500  # no warm up
  lr_steps_rel: [ 0.25, 0.5, 0.7, 0.8] # [0.2, 0.35, 0.5, 0.65, 0.8, 0.95]  # [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5

  weight_l1: 0
  # flow_warm_up_iter: -1
  weight_fl: 1

  niter: 40000 #200000
  val_freq: 500

#### validation settings
val:
  # heats: [ 0.0, 0.5, 0.75, 1.0 ]
  n_sample: 4

test:
  heats: [ 0.0, 0.7, 0.8, 0.9 ]

#### logger
logger:
  # Debug print_freq: 100
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
